### ISSUE TITLE
[1] Configure cinder-csi storageclass from ansible

### ISSUE THREAD

**Issue by OlleLarsson** [elastisys/compliantkubernetes-kubespray#110]
**Is your feature request related to a problem?**
When deploying on Openstack with cinder enabled, the storageclass `cinder-csi` is not default nor is volume expansion enabled.

**Describe the solution you'd like**
Enabling volume expansion and setting it to be the deafult storageclass is done by default on the supportet clouds.
See [kubespray](https://github.com/kubernetes-sigs/kubespray/blob/v2.16.0/roles/kubernetes-apps/persistent_volumes/cinder-csi/defaults/main.yml#L2-L7) for variables.

**Describe alternatives you've considered**

**Additional context**

**Definition of done:**
The cinder-csi is the deafult storageclass and volume expansion is enabled.

**Comment by viktor-f** [comment]
During some other testing I tried adding this to my group_vars, doing some changes, and it got picked up by ansible. So that seems to work fine.
```yaml
storage_classes:
  - name: cinder-csi
    is_default: false
    parameters:
      availability: nova
      allowVolumeExpansion: false
```

So I would suggest that we use
```yaml
storage_classes:
  - name: cinder-csi
    is_default: true
    parameters:
      availability: nova
      allowVolumeExpansion: true
```
