### ISSUE TITLE
[1] Reserve resources for system deamons

### ISSUE THREAD

**Issue by OlleLarsson** [elastisys/compliantkubernetes-kubespray#15]
To avoid the host dying due to resource starvation we should reserve resources for the system components
```
Warning  SystemOOM                7m34s (x11 over 19h)  kubelet  (combined from similar events): System OOM encountered, victim process: influxd, pid: 12133
```
This seems to be configurable [here](https://github.com/elastisys/compliantkubernetes-kubespray/blob/c7d874d785d262f86850361c8d2b750df25a1a15/config/group_vars/k8s-cluster/k8s-cluster.yml#L339-L346).

**Comment by lentzi90** [comment]
For some suggestions on what numbers to use, see [what google uses for GKE](https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-architecture#node_allocatable).

**Comment by tordsson** [comment]
See: https://github.com/elastisys/ck8s/issues/581
and https://github.com/elastisys/ck8s-cluster-old/pull/39

**Comment by lentzi90** [comment]
I think we can close this issue. There are defaults in [kubespray](https://github.com/kubernetes-sigs/kubespray/blob/master/roles/kubernetes/node/defaults/main.yml#L25-L38) and they seem to do the job in the tests I have conducted. That said, we may need to tweak these defaults depending on the size of the nodes, amount of pods, size of the cluster, etc.

This is how I tested the reserved resources:
- Create a cluster with the default values for Kubespray from compliantkubernetes-kubespray.
- Check the `capacity` and `allocatable` resources on the nodes. I used nodes with 4 GB memory and 2 CPUs, which showed `4030600Ki` memory capacity, `3666056Ki` memory allocatable, 2 CPUs capacity and 1900m CPUs allocatable. This nicely matches the Kubespray defaults.
- Attempt to run a pod with various memory requests. As soon as the requested memory was more than available of the allocatable, it stayed `pending`, so the reserved resources seem to work fine for scheduling. (I could run the pod with a memory request of `3400Mi` but not with `3500Mi`. Note that there are some other pods also on the nodes so we cannot expect all of the allocatable resources.)
- Attempt to run a pod that actually uses various amounts of memory. The pod run fine as long as it used less or equal to the limit I found earlier (`3400Mi`). If I made it use more than this, the kubelet would warn about SystemOOM:
  ```
  Warning  SystemOOM  5m26s                kubelet  System OOM encountered, victim process: stress, pid: 81742
  ```
  However, it stayed Ready throughout this and no other pods were affected as far as I could tell.

For reference, the Pod manifest I used to test this is this:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: memory-demo
  namespace: mem-example
spec:
  #nodeName: <my-node-name>
  containers:
  - name: memory-demo-ctr
    image: polinux/stress
    resources:
      requests:
        memory: "3400Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "3400M", "--vm-hang", "1"]
```
It is taken from the [kubernetes documentation](https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/).
Note that you can set the `nodeName` to make it more predictable and easier to repeat specific tests if you have more than one Node in the cluster.
