### ISSUE TITLE
Add support for IP allowlisting with Upcloud loadbalanacers

### ISSUE THREAD

**Issue by davidumea** [elastisys/compliantkubernetes-kubespray#354]
**Is your feature request related to a problem? Please describe.**
We want to be able to support IP allowlisting on ingresses in Upcloud, for this we need to be able to see the client source IP.
Upcloud loadbalancers do not understand proxy protocol by default. They have recently added support for this in their loadbalancers, but that config is not exposed in Kubespray.

**Describe the solution you'd like**
Add support for proxy protocol in Upcloud loadbalancers and make sure it works as expected.

**Additional context**
I have created this branch in our Kubespray fork `v2.24.0+ipv6-node-local-dns+missing-tf-provider+upcloud-proxy-protocol` which includes config for this. (commit https://github.com/elastisys/kubespray/commit/f8c832c8a7d481b2e11b99102e1a62f9128bd508)

With this, setting `loadbalancer_proxy_protocol` to true in your `cluster.tfvars` enables proxy protocol in the loadbalancer and in the GUI it gets enabled correctly as expected, however I was not able to get it working with the ingresses I created in the K8s cluster. There may be some other features that needs to be enabled.

With apps installed, you can deploy this "whoami" service in a **privileged** namespace to check your source IP
<details>
  <summary>Manifests</summary>

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - image: traefik/whoami
        args:
          - --port
          - "10080"
        name: whoami
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 5m
            memory: 25Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        ports:
        - name: web
          containerPort: 10080
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
spec:
  ports:
  - name: web
    targetPort: 10080
    port: 10080
  selector:
    app: whoami
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: whoami-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: <domain>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whoami
            port:
              name: web
  tls:
  - hosts:
    - <domain>
    secretName: whoami
```

</details>

One thing to note is that proxy protocol needs to be enabled in both the LB frontend and backend:
![image](https://github.com/elastisys/kubespray/assets/22236722/2415d417-895a-4d2d-893a-0339b62d161a)

**Definition of done:**
We can do IP allowlisting on ingresses with Upcloud loadbalancers.
